version: '3'

services:
  laravel-web-site-server:
    build: ./provisioning
    image: laravel-web-site
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./:/application:cached

  horizon:
    build: ./provisioning
    image: laravel-web-site
    command: php artisan horizon
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=web_site_DB
      - MYSQL_USER=porloscerros
      - MYSQL_PASSWORD=secret
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  mysql-test:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - laravel-web-site-server

  redis:
    image: redis
    ports:
      - "6379:6379"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - "8082:80"
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql
      restart: always
      depends_on:
        - mysql
